# Generated by Django 2.1.7 on 2019-03-12 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiflexmeterVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalLocationMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Longitude')),
                ('altitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Altitude')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('physicallocationmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mfm_beheerportaal.PhysicalLocationMixin')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('router', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfm_beheerportaal.Organisation')),
            ],
            bases=('mfm_beheerportaal.physicallocationmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Multiflexmeter',
            fields=[
                ('physicallocationmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mfm_beheerportaal.PhysicalLocationMixin')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Identifier')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='Created on')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfm_beheerportaal.Organisation')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfm_beheerportaal.MultiflexmeterVersion')),
            ],
            bases=('mfm_beheerportaal.physicallocationmixin', models.Model),
        ),
    ]
