# Generated by Django 2.2 on 2019-04-07 12:50

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiflexmeterVersion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version_major', models.IntegerField(verbose_name='Major version')),
                ('version_minor', models.IntegerField(verbose_name='Minor version')),
                ('version_patch', models.IntegerField(verbose_name='Patch version')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('abbreviation', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.Group')),
                ('abbreviation', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='WNS',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Multiflexmeter',
            fields=[
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Longitude')),
                ('altitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Altitude')),
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Identifier')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='Created on')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfm_beheerportaal.Network')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfm_beheerportaal.Organisation')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfm_beheerportaal.MultiflexmeterVersion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Longitude')),
                ('altitude', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Altitude')),
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Identifier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('router', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfm_beheerportaal.Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
