# Generated by Django 2.1.7 on 2019-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfm_beheerportaal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
            ],
        ),
    ]
